---
apiVersion: v1
kind: Secret
metadata:
  name: conv-app-secrets-common
  namespace: {{ $.Values.common.namespace }}
type: Opaque
data:
  VITE_DOMAIN: {{ .Values.app.domain | b64enc | quote }}
  AMQP_USER_NAME: {{ .Values.rabitmq.user_name | b64enc | quote }}
  AMQP_USER_PASSWORD: {{ .Values.rabitmq.user_password | b64enc | quote }}
  AMQP_HOSTNAME: {{ .Values.rabitmq.hostname | b64enc }}
  AMQP_EXCHANGE: {{ .Values.rabitmq.exchange | b64enc }}
  AMQP_QUEUE: {{ .Values.rabitmq.queue | b64enc }}
