---
apiVersion: v1
kind: Secret
metadata:
  name: conv-app-secrets
  namespace: conv-app
type: Opaque
data:
  RABBITMQ_DEFAULT_USER: R0VOcm9vdA==
  RABBITMQ_DEFAULT_PASS: Qkh6L1cySWQrR3UxWDJ1OCpKb1Fn
  SEED_USERNAME: RklSU1Ryb290
  SEED_USER_PASSWORD: cCpBcHBQLUhzcDZDSWkrWWZOZ0FUMA==
