---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Values.common.name }}-configmaps-vars
  namespace: {{ .Values.common.namespace }}
data:
  WHITE_DOMAIN: "{{ .Values.net.protocol }}://{{ .Values.net.host }}"
