---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.common.name }}-deployment
  namespace: {{ .Values.common.namespace }}
spec:
  replicas: {{ .Values.container.replicas }}
  selector:
    matchLabels:
      components: {{ .Values.container.components }}
  template:
    metadata:
      labels:
        components: {{ .Values.container.components }}
    spec:
      containers:
      - name: {{ .Values.common.name }}
        image: "{{ .Values.container.image_name }}:{{ .Values.container.image_version }}"
        ports:
        - containerPort: {{ .Values.container.port_num }}
        resources:
          limits: {{ .Values.container.limits | toYaml | nindent 12 }}
        env:
        - name: WHITE_DOMAIN
          valueFrom:
            configMapKeyRef:
              name: {{ .Values.common.name }}-configmaps-vars
              key: WHITE_DOMAIN
