---
apiVersion: v1
kind: Service
metadata:
  name: "{{ .Values.common.name }}-{{ .Values.net.service_type }}"
  namespace: {{ .Values.common.namespace }}
spec:
  type: ClusterIP
  ports:
  - port: {{ .Values.container.port_num }}
    protocol: {{ .Values.container.port_protocol }}
  selector:
    components: {{ .Values.container.components }}
