common:
  namespace: "conv-app"
  name: "conv-app"

container:
  components: frontend-conv
  image_name: antonlarichev/conv-app
  image_version: 1.2
  replicas: 1
  port_num: 80
  port_protocol: TCP
  limits:
    memory: "320Mi"
    cpu: "200m"

net:
  host: "conv.test"
  protocol: http
  service_type: clusterip
